import {
  BarChart3,
  Hash,
  Activity,
  TrendingUp,
  PieChart,
  CircleDot,
  Layers,
  Play,
  CircleCheck,
  ArrowRight,
  AlertTriangle,
  Users,
} from "lucide-react";
import type { WidgetType, WidgetDefinition, WidgetPickerItem } from "@/types/dashboard";

export const WIDGET_REGISTRY: Record<WidgetType, WidgetDefinition> = {
  stat: {
    type: "stat",
    label: "Stat Card",
    description: "Single metric with icon and description",
    icon: Hash,
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 6, h: 3 },
    defaultSettings: { metric: "total" },
  },
  chart: {
    type: "chart",
    label: "Chart",
    description: "Visual data chart (bar, pie, donut)",
    icon: BarChart3,
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 3, h: 3 },
    maxSize: { w: 12, h: 8 },
    defaultSettings: { chartType: "bar", dataDimension: "status", showLegend: true },
  },
  progress: {
    type: "progress",
    label: "Progress Tracker",
    description: "Project timeline with completion and elapsed time",
    icon: TrendingUp,
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 3, h: 3 },
    maxSize: { w: 12, h: 6 },
    defaultSettings: {},
  },
  activity: {
    type: "activity",
    label: "Activity Feed",
    description: "Recent feature changes sorted by update time",
    icon: Activity,
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 3, h: 3 },
    maxSize: { w: 12, h: 8 },
    defaultSettings: { itemLimit: 10 },
  },
};

/** Pre-configured templates shown in the Add Widget picker */
export const WIDGET_PICKER_ITEMS: WidgetPickerItem[] = [
  // --- Stat card presets ---
  {
    key: "stat-total",
    type: "stat",
    label: "Total Features",
    description: "Count of all features in the project",
    icon: Layers,
    defaultSize: { w: 3, h: 2 },
    defaultSettings: { title: "Total Features", metric: "total" },
  },
  {
    key: "stat-in-progress",
    type: "stat",
    label: "In Progress",
    description: "Features currently being worked on",
    icon: Play,
    defaultSize: { w: 3, h: 2 },
    defaultSettings: { title: "In Progress", metric: "in_progress" },
  },
  {
    key: "stat-completed",
    type: "stat",
    label: "Completed",
    description: "Features that have been finished",
    icon: CircleCheck,
    defaultSize: { w: 3, h: 2 },
    defaultSettings: { title: "Completed", metric: "completed" },
  },
  {
    key: "stat-up-next",
    type: "stat",
    label: "Up Next",
    description: "Features ready to start",
    icon: ArrowRight,
    defaultSize: { w: 3, h: 2 },
    defaultSettings: { title: "Up Next", metric: "up_next" },
  },
  {
    key: "stat-overdue",
    type: "stat",
    label: "Overdue",
    description: "Features past their end date",
    icon: AlertTriangle,
    defaultSize: { w: 3, h: 2 },
    defaultSettings: { title: "Overdue", metric: "overdue" },
  },
  {
    key: "stat-avg-progress",
    type: "stat",
    label: "Avg Progress",
    description: "Average completion percentage",
    icon: TrendingUp,
    defaultSize: { w: 3, h: 2 },
    defaultSettings: { title: "Avg Progress", metric: "avg_progress" },
  },
  // --- Chart presets ---
  {
    key: "chart-bar-status",
    type: "chart",
    label: "Status Bar Chart",
    description: "Feature count by status",
    icon: BarChart3,
    defaultSize: { w: 6, h: 5 },
    defaultSettings: { chartType: "bar", dataDimension: "status", showLegend: true },
  },
  {
    key: "chart-bar-priority",
    type: "chart",
    label: "Priority Bar Chart",
    description: "Feature count by priority level",
    icon: BarChart3,
    defaultSize: { w: 6, h: 5 },
    defaultSettings: { chartType: "bar", dataDimension: "priority", showLegend: true },
  },
  {
    key: "chart-bar-team",
    type: "chart",
    label: "Team Workload",
    description: "Feature count per team",
    icon: Users,
    defaultSize: { w: 6, h: 5 },
    defaultSettings: { chartType: "bar", dataDimension: "team", showLegend: true },
  },
  {
    key: "chart-pie-status",
    type: "chart",
    label: "Status Pie Chart",
    description: "Status distribution as proportions",
    icon: PieChart,
    defaultSize: { w: 6, h: 5 },
    defaultSettings: { chartType: "pie", dataDimension: "status", showLegend: true },
  },
  {
    key: "chart-pie-priority",
    type: "chart",
    label: "Priority Pie Chart",
    description: "Priority split across features",
    icon: PieChart,
    defaultSize: { w: 6, h: 5 },
    defaultSettings: { chartType: "pie", dataDimension: "priority", showLegend: true },
  },
  {
    key: "chart-donut-status",
    type: "chart",
    label: "Completion Donut",
    description: "Completion rate as a donut chart",
    icon: CircleDot,
    defaultSize: { w: 6, h: 5 },
    defaultSettings: { chartType: "donut", dataDimension: "status", showLegend: true },
  },
  {
    key: "chart-donut-team",
    type: "chart",
    label: "Team Donut",
    description: "Team distribution as a donut chart",
    icon: CircleDot,
    defaultSize: { w: 6, h: 5 },
    defaultSettings: { chartType: "donut", dataDimension: "team", showLegend: true },
  },
  // --- Progress ---
  {
    key: "progress",
    type: "progress",
    label: "Progress Tracker",
    description: "Timeline with completion and time elapsed",
    icon: TrendingUp,
    defaultSize: { w: 6, h: 4 },
    defaultSettings: { title: "Timeline" },
  },
  // --- Activity ---
  {
    key: "activity",
    type: "activity",
    label: "Activity Feed",
    description: "Recent feature changes sorted by update time",
    icon: Activity,
    defaultSize: { w: 6, h: 5 },
    defaultSettings: { title: "Recent Activity", itemLimit: 10 },
  },
];
